# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Duan Le
title: Technical Lead
email: duanvnc@gmail.com
website: https://duanvnc.github.io

# Social links
twitter_username: lequocduan
github_username:  duanvnc
# facebook_username: duanvnc
# instagram_username: duanvnc
linkedin_username: lequocduan
# youtube_username: duanvnc

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  General:
    - 9+ years experience in software development.
    - Strong experience in software development mainly in Web Application Development.
    - Good experience in the analysis, design, development, and implementation of applications.
    - Good experience in project management, plan to schedule & estimate tasks, assign to team members.
    - Worked as an engineer & manager in both independent and inter-dependent environments.
    - English in communication, writing and reading skills.
    - Japanese Basic

  I am most skilled in: 
    - Languages: <mark>PHP</mark>, <mark>NodeJS</mark>, <mark>Javascript</mark>, <mark>ReactJS</mark>, <mark>SailsJs</mark>, <mark>CoffeeScript</mark>, <mark>HTML</mark>, <mark>CSS</mark>
    - Databases: <mark>MySQL</mark>, <mark>Elasticsearch</mark>, <mark>Firebase</mark>, <mark>SQL Server</mark>, <mark>MongoDB</mark>, <mark>Redis</mark>
    - AWS Stacks: <mark>RDS</mark>, <mark>EC2</mark>, <mark>Lambda</mark>, <mark>Route53</mark>, <mark>Cloudfront</mark>, <mark>S3 Bucket</mark>, <mark>ECS</mark>, <mark>ECR</mark>, <mark>CodePipelines</mark>, <mark>CodeBuild</mark>, <mark>CodeDeploy</mark>, <mark>CodeCommit</mark>, <mark>ElastiCache</mark>, <mark>IAM</mark>, <mark>CloudWatch</mark>, <mark>SQS</mark>, <mark>SES</mark>, <mark>SNS</mark>
    - Frameworks: <mark>Symfony</mark>, <mark>Laravel</mark>, <mark>CakePHP</mark>, <mark>FuelPHP</mark>, <mark>Slim</mark>, <mark>Silex</mark>, <mark>SailsJS</mark>, <mark>LoopbackJS</mark>, <mark>ExpressJS</mark>, <mark>SocketIO</mark>, <mark>MeteorJS</mark>
    - CMS: <mark>Drupal</mark>, <mark>Wordpress</mark>, <mark>Magento</mark>
    - Webservers: <mark>Nginx</mark>, <mark>Apache</mark>
    - Development Tools: <mark>Vagrant</mark>, <mark>Docker</mark>, <mark>Github</mark>, <mark>Jenkins</mark>, <mark>Ansible</mark>
    - OS: <mark>Linux</mark>, <mark>Unix</mark>, <mark>Windows</mark>, <mark>MacOS</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Reading
   - Swimming
   - Fishing
   - Farming
   - Knitting

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
